### ISSUE TITLE
wsidicomizer 0.15.1 does not work with the current zarr 3.0.1

### ISSUE THREAD

**Issue by fedorov** [imi-bigpicture/wsidicomizer#117]
I tried the latest wsidicomizer 0.15.1, and import failed with the error below.

Downgrading zarr to 2.14.18 fixes the issue. 

```
ImportError                               Traceback (most recent call last)
[<ipython-input-1-6d7dc75e9dfa>](https://localhost:8080/#) in <cell line: 0>()
      5 import shutil
      6 from pathlib import Path
----> 7 from wsidicomizer import WsiDicomizer
      8 from typing import List
      9 

7 frames
[/usr/local/lib/python3.11/dist-packages/tiffslide/_zarr.py](https://localhost:8080/#) in <module>
     15 from tifffile import TiffFile
     16 from tifffile import ZarrTiffStore
---> 17 from zarr.storage import BaseStore
     18 from zarr.storage import FSStore
     19 from zarr.storage import KVStore as _KVStore

ImportError: cannot import name 'BaseStore' from 'zarr.storage' (/usr/local/lib/python3.11/dist-packages/zarr/storage/__init__.py)
```

**Comment by DanielaSchacherer** [comment]
I had the same experience unfortunately.
